# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89d34ace755516476ef869c31b2f6ab07fa3645b22bfc2761f3518cce14aa93c81240bb006808d9e3fa104ac3a9b6d00c49c609798726d78602b1e49a0abcfee

test:
  secret_key_base: e7d3246a97c5ea119234681c41edfbae25382f319cdd83084d97861b9eda7081364e1eb4dad3025495da9e1c53f29555392dd823fe84fda47b373919f8cfc7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
